# Generated by Django 5.0.1 on 2024-01-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_alimentados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('localizacao', models.CharField(max_length=100)),
                ('escola', models.CharField(max_length=100)),
            ],
        ),
    ]
